/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Keiner
 */
public class GestionSolicitud extends javax.swing.JFrame {

    /**
     * Creates new form GestionSolicitud
     */
    public GestionSolicitud() {
        initComponents();
        
        //jTextFieldgestionNombre.setText("Prueba");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldgestionContrase = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jStablaSolicitudAtendidas = new javax.swing.JScrollPane();
        jTableSolicitudAtendida = new javax.swing.JTable();
        jStablaSolicitudesSinAtender = new javax.swing.JScrollPane();
        jTableSolicitudes = new javax.swing.JTable();
        jTextField1CodigoSolicitud = new javax.swing.JTextField();
        jButtonAtender = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonMostrarSolAtendidas = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1Tiempo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Gestion de solicitud");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(380, 10, 185, 41);
        jPanel1.add(jTextFieldgestionContrase);
        jTextFieldgestionContrase.setBounds(150, 30, 120, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Solicitudes Atendidas");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 270, 166, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Solicitudes Sin Atender");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 130, 180, 22);

        jLabel4.setText("Codigo De La Empresa");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(161, 685, 107, 14);

        jTableSolicitudAtendida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Solicitud", "Nombre Empresa", "Codigo Empresa", "Nombre Funcionario", "Contraseña Funcionario", "Estado Solicitud"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jStablaSolicitudAtendidas.setViewportView(jTableSolicitudAtendida);

        jPanel1.add(jStablaSolicitudAtendidas);
        jStablaSolicitudAtendidas.setBounds(230, 80, 570, 110);

        jTableSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Solicitud", "Nombre Empresa", "Codigo Empresa", "Nombre Funcionaio", "Estado Solicitud"
            }
        ));
        jStablaSolicitudesSinAtender.setViewportView(jTableSolicitudes);

        jPanel1.add(jStablaSolicitudesSinAtender);
        jStablaSolicitudesSinAtender.setBounds(230, 220, 570, 110);
        jPanel1.add(jTextField1CodigoSolicitud);
        jTextField1CodigoSolicitud.setBounds(180, 400, 120, 20);

        jButtonAtender.setText("Atender");
        jPanel1.add(jButtonAtender);
        jButtonAtender.setBounds(320, 400, 100, 23);

        jLabel5.setText("Codigo Solicitud");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 400, 100, 14);

        jButtonMostrarSolAtendidas.setText("Listar Solicitudes");
        jPanel1.add(jButtonMostrarSolAtendidas);
        jButtonMostrarSolAtendidas.setBounds(40, 80, 140, 23);

        jLabel6.setText(" Ingrese Su Contraseña");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 30, 114, 14);
        jPanel1.add(jTextField1Tiempo);
        jTextField1Tiempo.setBounds(600, 400, 100, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionSolicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAtender;
    public javax.swing.JButton jButtonMostrarSolAtendidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jStablaSolicitudAtendidas;
    public javax.swing.JScrollPane jStablaSolicitudesSinAtender;
    public javax.swing.JTable jTableSolicitudAtendida;
    public javax.swing.JTable jTableSolicitudes;
    public javax.swing.JTextField jTextField1CodigoSolicitud;
    public javax.swing.JTextField jTextField1Tiempo;
    public javax.swing.JTextField jTextFieldgestionContrase;
    // End of variables declaration//GEN-END:variables
}
