/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author KEINER
 */
public class RegistrarseLogin extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarseLogin
     */
    public RegistrarseLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1nombreRegistro = new javax.swing.JTextField();
        jTextField2contraseñaregistro = new javax.swing.JTextField();
        jComboBox1tipodecuenta = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField3Apellidoreguistro = new javax.swing.JTextField();
        jButton1reguistrarpersona = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(220, 340));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 19, 70, 20);

        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 97, 80, 30);

        jLabel3.setText("Tipo De Cuenta");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 137, 90, 20);

        jTextField1nombreRegistro.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jTextField1nombreRegistro);
        jTextField1nombreRegistro.setBounds(90, 20, 120, 20);

        jTextField2contraseñaregistro.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jTextField2contraseñaregistro);
        jTextField2contraseñaregistro.setBounds(90, 100, 114, 20);

        jComboBox1tipodecuenta.setBackground(new java.awt.Color(204, 204, 255));
        jComboBox1tipodecuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja Una opcion", "Usuario", "Administrador" }));
        jPanel1.add(jComboBox1tipodecuenta);
        jComboBox1tipodecuenta.setBounds(120, 140, 126, 20);

        jLabel4.setText("Apellido");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 53, 60, 20);

        jTextField3Apellidoreguistro.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jTextField3Apellidoreguistro);
        jTextField3Apellidoreguistro.setBounds(80, 50, 108, 20);

        jButton1reguistrarpersona.setText("Registrar");
        jPanel1.add(jButton1reguistrarpersona);
        jButton1reguistrarpersona.setBounds(102, 200, 100, 23);

        jButtonRegresar.setText("Regresar");
        jPanel1.add(jButtonRegresar);
        jButtonRegresar.setBounds(208, 241, 90, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoLogin.gif"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 400, 280);

        jTabbedPane1.addTab("Reguistro De Persona", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 400, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarseLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarseLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1reguistrarpersona;
    public javax.swing.JButton jButtonRegresar;
    public javax.swing.JComboBox<String> jComboBox1tipodecuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField jTextField1nombreRegistro;
    public javax.swing.JTextField jTextField2contraseñaregistro;
    public javax.swing.JTextField jTextField3Apellidoreguistro;
    // End of variables declaration//GEN-END:variables
}
