/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author KEINER
 */
public class VistaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdministrador
     */
    public VistaAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaqueja1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaqueja2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaqueja3 = new javax.swing.JTextArea();
        jTextFieldnombre_empres = new javax.swing.JTextField();
        jTextFieldtipo_empresa = new javax.swing.JTextField();
        jTextFieldcodigo_empresa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxestado_queja1 = new javax.swing.JComboBox<>();
        jComboBoxestado_queja2 = new javax.swing.JComboBox<>();
        jComboBoxestado_queja3 = new javax.swing.JComboBox<>();
        jButtonRegistrar_empresa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxarea_empresa = new javax.swing.JComboBox<>();
        jButtonBuscar_por_codigo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButtonRegresarLogin = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxAsignarFuncionario = new javax.swing.JComboBox<>();
        jButtonAsignar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 580));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Nombre De La Empresa");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 41, 150, 14);

        jLabel2.setText("Tipo De Empresa");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 73, 110, 14);

        jLabel3.setText("Codigo De La Empresa");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 119, 130, 14);

        jLabel4.setText(" Queja o Reclamo 1");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 215, 140, 14);

        jTextAreaqueja1.setColumns(20);
        jTextAreaqueja1.setRows(5);
        jScrollPane1.setViewportView(jTextAreaqueja1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 247, 223, 96);

        jLabel5.setText(" Queja o Reclamo 2");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(281, 215, 120, 14);

        jTextAreaqueja2.setColumns(20);
        jTextAreaqueja2.setRows(5);
        jScrollPane2.setViewportView(jTextAreaqueja2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(267, 247, 223, 96);

        jLabel6.setText(" Queja o Reclamo 3");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 372, 130, 14);

        jTextAreaqueja3.setColumns(20);
        jTextAreaqueja3.setRows(5);
        jScrollPane3.setViewportView(jTextAreaqueja3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 390, 223, 96);
        jPanel1.add(jTextFieldnombre_empres);
        jTextFieldnombre_empres.setBounds(159, 38, 215, 20);
        jPanel1.add(jTextFieldtipo_empresa);
        jTextFieldtipo_empresa.setBounds(159, 70, 191, 20);
        jPanel1.add(jTextFieldcodigo_empresa);
        jTextFieldcodigo_empresa.setBounds(159, 116, 110, 20);

        jLabel7.setText("Estado De La Queja o Reclamo");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(395, 372, 190, 14);

        jLabel8.setText(" Queja o Reclamo 1");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(283, 404, 110, 14);

        jLabel9.setText(" Queja o Reclamo 2");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(283, 442, 110, 14);

        jLabel10.setText(" Queja o Reclamo 3");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(283, 480, 110, 14);

        jComboBoxestado_queja1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Atendida", "No Atendida", "En Proceso" }));
        jPanel1.add(jComboBoxestado_queja1);
        jComboBoxestado_queja1.setBounds(413, 401, 79, 20);

        jComboBoxestado_queja2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Atendida", "No Atendida", "En Proceso" }));
        jPanel1.add(jComboBoxestado_queja2);
        jComboBoxestado_queja2.setBounds(413, 439, 79, 20);

        jComboBoxestado_queja3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Atendida", "No Atendida", "En Proceso" }));
        jPanel1.add(jComboBoxestado_queja3);
        jComboBoxestado_queja3.setBounds(413, 477, 79, 20);

        jButtonRegistrar_empresa.setText("Registrar Empresa");
        jPanel1.add(jButtonRegistrar_empresa);
        jButtonRegistrar_empresa.setBounds(400, 69, 180, 23);

        jLabel11.setText("Area De La Empresa Que Solicitara La Queja");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 180, 280, 14);

        jComboBoxarea_empresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja Un Opcion", "Contabilidad", "Sistemas", "Bienestar", "Gerencia", "Presidencia", "Area De Labores", " " }));
        jPanel1.add(jComboBoxarea_empresa);
        jComboBoxarea_empresa.setBounds(300, 180, 121, 20);

        jButtonBuscar_por_codigo.setText("Buscar");
        jPanel1.add(jButtonBuscar_por_codigo);
        jButtonBuscar_por_codigo.setBounds(309, 115, 100, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Administrador");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(251, 6, 90, 30);

        jButtonRegresarLogin.setText("Cerrar Sesion");
        jPanel1.add(jButtonRegresarLogin);
        jButtonRegresarLogin.setBounds(500, 460, 130, 23);

        jLabel14.setText("Asignar Solicitud");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(490, 130, 130, 14);

        jPanel1.add(jComboBoxAsignarFuncionario);
        jComboBoxAsignarFuncionario.setBounds(460, 160, 170, 20);

        jButtonAsignar.setText("Asignar");
        jPanel1.add(jButtonAsignar);
        jButtonAsignar.setBounds(510, 200, 110, 23);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(-360, -20, 1020, 550);

        jTabbedPane1.addTab("Crear Empresa", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 663, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAsignar;
    public javax.swing.JButton jButtonBuscar_por_codigo;
    public javax.swing.JButton jButtonRegistrar_empresa;
    public javax.swing.JButton jButtonRegresarLogin;
    public javax.swing.JComboBox<String> jComboBoxAsignarFuncionario;
    public javax.swing.JComboBox<String> jComboBoxarea_empresa;
    public javax.swing.JComboBox<String> jComboBoxestado_queja1;
    public javax.swing.JComboBox<String> jComboBoxestado_queja2;
    public javax.swing.JComboBox<String> jComboBoxestado_queja3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextArea jTextAreaqueja1;
    public javax.swing.JTextArea jTextAreaqueja2;
    public javax.swing.JTextArea jTextAreaqueja3;
    public javax.swing.JTextField jTextFieldcodigo_empresa;
    public javax.swing.JTextField jTextFieldnombre_empres;
    public javax.swing.JTextField jTextFieldtipo_empresa;
    // End of variables declaration//GEN-END:variables
}
