package Modelo;
// Generated 14-may-2018 17:34:17 by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer idLogin;
     private String nombre;
     private String contrasena;
     private String tipoCuenta;
     private String apellido;

    public Login() {
    }

    public Login(String nombre, String contrasena, String tipoCuenta, String apellido) {
       this.nombre = nombre;
       this.contrasena = contrasena;
       this.tipoCuenta = tipoCuenta;
       this.apellido = apellido;
    }
   
    public Integer getIdLogin() {
        return this.idLogin;
    }
    
    public void setIdLogin(Integer idLogin) {
        this.idLogin = idLogin;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getTipoCuenta() {
        return this.tipoCuenta;
    }
    
    public void setTipoCuenta(String tipoCuenta) {
        this.tipoCuenta = tipoCuenta;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    
    public String ToString(){
        return String.format("%s\n",this.nombre);
    }

}


