package Modelo;
// Generated 14-may-2018 17:34:17 by Hibernate Tools 4.3.1



/**
 * SolicitudesAtendidas generated by hbm2java
 */
public class SolicitudesAtendidas  implements java.io.Serializable {


     private int idSolicitudesAtendidas;
     private String nombreEmpresa;
     private String codigoEmpresa;
     private String nombreFuncionario;
     private String contrasenaFuncionario;
     private String estadosolicitud1;

    public SolicitudesAtendidas() {
    }

	
    public SolicitudesAtendidas(int idSolicitudesAtendidas) {
        this.idSolicitudesAtendidas = idSolicitudesAtendidas;
    }
    public SolicitudesAtendidas(int idSolicitudesAtendidas, String nombreEmpresa, String codigoEmpresa, String nombreFuncionario, String contrasenaFuncionario) {
       this.idSolicitudesAtendidas = idSolicitudesAtendidas;
       this.nombreEmpresa = nombreEmpresa;
       this.codigoEmpresa = codigoEmpresa;
       this.nombreFuncionario = nombreFuncionario;
       this.contrasenaFuncionario = contrasenaFuncionario;
    }
   
    public int getIdSolicitudesAtendidas() {
        return this.idSolicitudesAtendidas;
    }
    
    public void setIdSolicitudesAtendidas(int idSolicitudesAtendidas) {
        this.idSolicitudesAtendidas = idSolicitudesAtendidas;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getCodigoEmpresa() {
        return this.codigoEmpresa;
    }
    
    public void setCodigoEmpresa(String codigoEmpresa) {
        this.codigoEmpresa = codigoEmpresa;
    }
    public String getNombreFuncionario() {
        return this.nombreFuncionario;
    }
    
    public void setNombreFuncionario(String nombreFuncionario) {
        this.nombreFuncionario = nombreFuncionario;
    }
    public String getContrasenaFuncionario() {
        return this.contrasenaFuncionario;
    }
    
    public void setContrasenaFuncionario(String contrasenaFuncionario) {
        this.contrasenaFuncionario = contrasenaFuncionario;
    }
    
    public String getestadosolicitud1(){
        return this.estadosolicitud1;
    }
    
    public void setestadosolicitud1(String estadosolicitud1){
        this.estadosolicitud1 = estadosolicitud1;
    }




}


